---
- name: Nginx
  #hosts: tag_reddit-app # for dynamic inv
  hosts: app
  become: true
  tasks:
    - name: Update repositories cache
      apt:
        update_cache: yes
  roles:
  - role: nginx
    nginx_http_params:
      - sendfile "on"
      - access_log "/var/log/nginx/access.log"
    nginx_sites:
      bar:
        - listen 80
        - | 
          location / {
            proxy_set_header X-Forwarded-Host $host;
            proxy_set_header X-Forwarded-Server $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_pass http://localhost:9292;
          }
